Update passwords to more directly reference using a password manager
Lullabot/information-security-policy pull request #250
Opened 2024-09-26 17:49 UTC by deviantintegral

This is very much a first draft for our meeting next week. Others may have different takes on where this doc should go, so feel free to push edits here or file a competing pull request!

2024-10-01 13:24 UTC, YesCT commented on access/passwords.md
> +The first layer of defense that we have for our online accounts is the PIN, passcode, or password. As such, it is extremely important to use good, unique passwords, and keep them well protected. A go
```suggestion
The first layer of defense that we have for our online accounts is the PIN, passcode, or password. As such, it is extremely important to use good, unique passwords, and keep them well protected. A good password is difficult for people to guess and machines to brute-force. Contrary to popular belief, the inclusion of numbers, characters, or mixed case does not matter nearly as much as the length of the password itself.
```

2024-10-01 13:26 UTC, YesCT commented on access/passwords.md
> +The first layer of defense that we have for our online accounts is the PIN, passcode, or password. As such, it is extremely important to use good, unique passwords, and keep them well protected. A go
"consists is" -> "is"
"hard" -> "difficult" ... personal preference. difficult is more accurate, and translates to similar words in other languages.

2024-10-01 13:31 UTC, YesCT commented on access/passwords.md
> +With the use of a password manager, you no longer need to memorize each password. Passwords will be filled automatically, or can be copied and pasted in. The length of a password is its primary stren
Nice documentation of the reason for 16 chars. That will help us know when to re-evaluate that min.

2024-10-01 13:33 UTC, YesCT requested changes
Nice improvement. I left some thoughts. One grammar suggestion seems worth requesting changes. Others aren't blocking.

2024-10-02 14:04 UTC, YesCT approved these changes
Nice improvement.

2024-10-15 22:14 UTC, deviantintegral commented
We also discussed this today and it's good to go. Thanks team!

2024-10-15 22:16 UTC, merged